[package]
name = "rust-mini"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
barrel = { version = "0.7.0", features = ["sqlite3"] }
refinery = { version = "0.8.7", features = ["rusqlite", "postgres"] }
rusqlite = "0.28.0"
